// ===== メッセージUIの宣言データ =====
const MESSAGE_REVIEW_STORAGE_KEY='wake7-message-review';
const MESSAGE_REVIEW_LAST_CLEAR_STORAGE_KEY='wake7-message-review-last-clear';
let messageReviewEntries=[],messageReviewIndex=0;
const MESSAGE_ROADMAP_MASTERS=Object.freeze(['primary','mastery','satori','satoriIntro','secondLapIntro','awakening','trainingWelcome']);
const MESSAGE_MASTERY_BOARD_MASTERS=Object.freeze(['mastery','satori','awakening']);
const MESSAGE_TILTED_BOARD_MASTERS=Object.freeze(['satori','awakening']);
const INTRO_MILESTONE_COPY=Object.freeze({
  satoriIntro:['satoriIntroTitle','satoriIntroText'],
  secondLapIntro:['secondLapTitle','secondLapText'],
  trainingWelcome:['trainingWelcomeTitle','trainingWelcomeText']
});
const VOLUME_NEXT_RULES=Object.freeze({
  ja:[
    '「破」からは、ヒントが使えなくなります。',
    '「急」では途中から最短4手の問題です。\nスワイプ中は残り最短手数が「？」になります。',
    '「極」では残り最短手数が表示されません。\nかわりに回数限定で「残り手数」のボタンが使えますが、これも途中から使用回数が減っていきます。'
  ]
});
function messageReviewEntryKey(entry){const kind=entry.awakened?'master:awakening':entry.satori?'satori':entry.master?'master:'+entry.master:entry.boardQuiz?'board-quiz':entry.quiz!==undefined?'quiz':'text';return (entry.awakened||entry.satori?'satori':entry.extra?'extra':'primary')+':'+entry.index+':'+kind;}
function finalizeMessageReviewEntries(entries){return entries.map(entry=>{const messageId=entry.master||clearContentKey(!!entry.extra,entry.index);const message=entry.master?milestoneMessageDescriptor(entry.master):clearMessageDescriptor(!!entry.extra,entry.index);return {...entry,messageId,message};});}
function messageReviewProgressSets(){return {primary:activeLap===2?lap1ClearedStages:clearedStages,extra:activeLap===2?lap1ClearedExtraStages:clearedExtraStages,satori:activeLap===2?lap1ClearedSatoriStages:clearedSatoriStages};}
function collectPrimaryMessageReviewEntries(reviewPrimary){const entries=[];for(let i=0;i<STAGES.length;i++){if(!reviewPrimary.has(i))continue;if(i===ACADEMY_STAGE_COUNT-1){if(speedTrainingTrialCleared){entries.push({master:'primary',extra:false,index:i});const before=clearContentBefore(false,TRAINING_STAGE_START);if(before?.dialog)entries.push({master:before.dialog,extra:false,index:i});}continue;}const text=stageClearTextAt(false,i);if(text)entries.push({extra:false,index:i,text,art:stageClearArtAt(false,i)});const primaryEntry=clearContentAt(false,i);if(primaryEntry&&primaryEntry.quiz)entries.push({extra:false,index:i,quiz:resolveLocaleText(primaryEntry.quiz),art:stageClearArtAt(false,i)});}return entries;}
function collectExtraMessageReviewEntries(reviewExtra){const entries=[];for(let i=0;i<EXTRA_STAGES.length;i++){if(!reviewExtra.has(i))continue;if((i+1)%MASTER_VOLUME_SIZE===0){if(i===EXTRA_STAGES.length-1){if(speedMasteryTrialCleared)entries.push({master:'mastery',extra:true,index:i});}else if(i!==29||speedIntermediateTrialCleared)entries.push({master:'volume',extra:true,index:i});continue;}const text=stageClearTextAt(true,i);if(text)entries.push({extra:true,index:i,text,art:stageClearArtAt(true,i)});const extraEntry=clearContentAt(true,i);if(extraEntry&&extraEntry.boardQuiz)entries.push({extra:true,index:i,boardQuiz:true});if(extraEntry&&extraEntry.quiz)entries.push({extra:true,index:i,quiz:resolveLocaleText(extraEntry.quiz),art:stageClearArtAt(true,i)});}return entries;}
function collectMessageReviewMilestones(reviewMastered,reviewSatoriMastered){const entries=[];if(reviewMastered&&speedMasteryTrialCleared)entries.push({master:'satoriIntro',extra:true,index:EXTRA_STAGES.length-1});if(reviewSatoriMastered||hasSatoriReward())entries.push({master:'satori',satori:true,index:SATORI_STAGES.length-1});if(secondLapUnlocked)entries.push({master:'secondLapIntro',extra:true,index:SATORI_STAGES.length-1});if(awakenedGranted)entries.push({master:'awakening',awakened:true,index:SATORI_STAGES.length-1});return entries;}
function buildMessageReviewEntries(){const entries=[];const {primary:reviewPrimary,extra:reviewExtra,satori:reviewSatori}=messageReviewProgressSets();const {primary:reviewPrimaryDone,extra:reviewMastered,satori:reviewSatoriMastered}=messageReviewCompletion({primary:reviewPrimary,extra:reviewExtra,satori:reviewSatori});entries.push(...collectPrimaryMessageReviewEntries(reviewPrimary));if(!reviewPrimaryDone){if(secondLapUnlocked)entries.push({master:'secondLapIntro',extra:true,index:SATORI_STAGES.length-1});return finalizeMessageReviewEntries(entries);}entries.push(...collectExtraMessageReviewEntries(reviewExtra));entries.push(...collectMessageReviewMilestones(reviewMastered,reviewSatoriMastered));return finalizeMessageReviewEntries(entries);}
function messageReviewCompletion(sets){return {primary:STAGES.every((_,index)=>sets.primary.has(index)),extra:EXTRA_STAGES.every((_,index)=>sets.extra.has(index)),satori:SATORI_STAGES.every((_,index)=>sets.satori.has(index))};}
function messageReviewPlace(entry){if(entry.awakened)return tr('awakenedTitle');if(entry.satori)return currentLang==='ja'?'悟りへの道・第'+(entry.index+1)+'問 クリア':tr('satoriTitle');if(entry.master==='satoriIntro')return currentLang==='ja'?'悟りへの道の案内':tr('satoriIntroTitle');if(entry.master==='secondLapIntro')return currentLang==='ja'?'二周目の案内':tr('secondLapTitle');if(entry.master==='trainingWelcome')return currentLang==='ja'?'だるま修行の案内':tr('trainingWelcomeTitle');if(!entry.extra){if(currentLang!=='ja')return tr('stageAria',{n:entry.index+1,par:STAGES[entry.index].par});const {section,position}=primarySectionPosition(entry.index);return tr(section.labelKey)+' 第'+position+'問 クリア';}const volume=Math.floor(entry.index/MASTER_VOLUME_SIZE)+1;return currentLang==='ja'?'名人への道 '+volumeLabel(volume)+'・第'+(entry.index%MASTER_VOLUME_SIZE+1)+'問 クリア':tr('extraStageAria',{n:entry.index+1,total:EXTRA_STAGES.length});}
function messageReviewStageContext(entry){if(entry.awakened)return tr('secondLapPath');if(entry.satori)return tr('satori')+' '+(entry.index+1)+' / '+SATORI_STAGES.length;if(entry.master==='satoriIntro')return tr('satori');if(entry.master==='secondLapIntro')return tr('secondLapPath');if(entry.master==='trainingWelcome')return tr('darumaTraining');if(!entry.extra){const {section,position:number}=primarySectionPosition(entry.index);return tr(section.labelKey)+' '+number+' / '+section.total;}const volume=Math.floor(entry.index/MASTER_VOLUME_SIZE)+1;const path=currentLang==='ja'?'名人への道・'+volumeLabel(volume):tr('allPatternsKind')+' '+volumeLabel(volume);return path+'　'+masterSubtitle(volume)+' '+(entry.index%MASTER_VOLUME_SIZE+1)+' / '+MASTER_VOLUME_SIZE;}
function configureMessageReviewHeader(entry){$('messageDialogTitle').textContent=tr('clear');$('messageDialogPlace').textContent=messageReviewPlace(entry);}
function rememberSpecialMessage(master){const entry=buildMessageReviewEntries().find(item=>item.master===master);if(!entry)return;const key=messageReviewEntryKey(entry);try{storage.set(MESSAGE_REVIEW_STORAGE_KEY,key);storage.set(MESSAGE_REVIEW_LAST_CLEAR_STORAGE_KEY,key);}catch(_){}}
function rememberClearedMessage(extra,index,satori=false){const entry=buildMessageReviewEntries().find(item=>!!item.satori===satori&&!!item.extra===extra&&item.index===index);if(!entry)return;const key=messageReviewEntryKey(entry);try{storage.set(MESSAGE_REVIEW_STORAGE_KEY,key);storage.set(MESSAGE_REVIEW_LAST_CLEAR_STORAGE_KEY,key);}catch(_){} }
function messageReviewView(){return {seal:$('messageMasterSeal'),rankText:$('messageRankText'),masterText:$('messageMasterText'),boardNote:$('messageMasterBoardNote'),rules:$('messageRules'),roadmap:$('messageRoadmap'),roadmapNote:$('messageRoadmapNote'),illustration:$('messageIllustration'),lessonCopy:$('messageTwoMoveLessonCopy'),lessonRule:$('messageTwoMoveLessonRule')};}
function messageReviewContent(entry){return entry?.message?.content||null;}
function messageReviewArt(entry){const content=messageReviewContent(entry);return entry?.art||content?.art||'';}
function configureMessageReviewType(entry){const content=messageReviewContent(entry),messageClearEntry=content||(entry.extra?clearContentAt(true,entry.index):null);$('messageDialogText').hidden=!!entry.master||entry.quiz!==undefined||!!entry.boardQuiz;$('messageQuiz').hidden=entry.quiz===undefined;$('messageBoardQuiz').hidden=!entry.boardQuiz;return messageClearEntry;}
function configureMessageReviewLinks(entry,messageClearEntry){const twoMoveCard=messageClearEntry?.twoMoveCard,guideCard=messageClearEntry?.guideCard,rankLink=messageClearEntry?.link==='rank',tipsLink=messageClearEntry?.link==='tips',patternsLink=messageClearEntry?.link==='patterns',link=$('messageRankLink');link.hidden=twoMoveCard===undefined&&!guideCard&&!rankLink&&!tipsLink&&!patternsLink;link.dataset.target=tipsLink?'tips':patternsLink?'patterns':twoMoveCard!==undefined?'card':guideCard?'guide':'rank';link.textContent=tipsLink?tr('tipGuideTitle')+' →':patternsLink?tr('twoMovePatternsLink')+' →':twoMoveCard!==undefined||guideCard?tr('detailsLink'):tr('rankLink');}
function isMilestoneMessage(entry){return !!entry?.master;}
function milestoneVolume(entry){return entry?.master==='primary'?0:Math.ceil((entry.index+1)/MASTER_VOLUME_SIZE);}
function resetMessageReviewView(entry,view){const {roadmap,roadmapNote}=view;$('messagePrev').textContent='← '+tr('prev');$('messageNext').textContent=tr('next')+' →';$('closeMessages').textContent=tr('close');$('messageStageContext').textContent=messageReviewStageContext(entry);$('messageDialogPlace').hidden=true;renderMasteryBoard('messageMasteryBoard',MESSAGE_MASTERY_BOARD_MASTERS.includes(entry.master),MESSAGE_TILTED_BOARD_MASTERS.includes(entry.master)?'satori-tilted':'gold');roadmap.hidden=!entry.master||!MESSAGE_ROADMAP_MASTERS.includes(entry.master);roadmapNote.hidden=true;view.boardNote.hidden=true;view.rules.hidden=true;view.seal.hidden=!entry.master;view.seal.classList.add('rank-seal');view.seal.classList.remove('rank-frame-seal','second-lap-mark');view.seal.tabIndex=0;view.rankText.hidden=true;view.masterText.hidden=true;}
function updateMessageReviewNavigation(entry){$('messagePrev').disabled=messageReviewIndex===0;$('messageNext').disabled=messageReviewIndex===messageReviewEntries.length-1;try{storage.set(MESSAGE_REVIEW_STORAGE_KEY,messageReviewEntryKey(entry));}catch(_){}
}
function moveMessageReview(delta){const next=messageReviewIndex+delta;if(next<0||next>=messageReviewEntries.length)return false;messageReviewIndex=next;renderMessageReview();return true;}
function configureMilestoneHeader(entry,title){$('messageDialogTitle').textContent=title;$('messageDialogPlace').textContent=messageReviewPlace(entry);}
function prepareMessageReview(entry){const art=messageReviewArt(entry),twoMoveLesson=lessonVariantFromArt(art),messageClearEntry=configureMessageReviewType(entry);configureMessageReviewLinks(entry,messageClearEntry);return {art,twoMoveLesson,messageClearEntry};}
function milestoneRenderer(entry){return MILESTONE_RENDERERS[entry.master]||MILESTONE_RENDERERS.volume;}
function messageReviewRenderer(entry){if(entry.quiz!==undefined)return MESSAGE_RENDERERS.quiz;if(entry.boardQuiz)return MESSAGE_RENDERERS.boardQuiz;return MESSAGE_RENDERERS.text;}
function renderMessageArtwork(art,twoMoveLesson,illustration,lessonCopy,lessonRule){const classByArt={'move-graph':art==='moveGraph','board-card':art.startsWith('twoMoveCard:')||art.startsWith('guideCard:'),'controls-art':art==='controls','navigation-art':art==='navigation','menu-art':art==='menuButtons','rank-badge-art':art==='rankBadgeArt','unwritten-art':art==='unwritten','cheer-art':art==='cheer','intro-guide-art':art==='introGuide','two-move-lesson-art':!!twoMoveLesson};Object.entries(classByArt).forEach(([className,enabled])=>illustration.classList.toggle(className,enabled));stopClearGuideBoard('messageClearGuideBoard');stopClearGuideBoard('messageTwoMoveLessonBoard');illustration.innerHTML=art==='introGuide'?'<svg id="messageClearGuideBoard" viewBox="14 0 293 310" aria-hidden="true"></svg>':twoMoveLesson?'<svg id="messageTwoMoveLessonBoard" viewBox="14 0 293 310" aria-hidden="true"></svg>':art?tipArt(art):'';if(art==='cheer'){const template=document.getElementById('message-cheer-caption-template');if(template){const caption=template.content.cloneNode(true);caption.querySelector('[data-cheer-caption]').textContent=tr('cheerCaption');illustration.append(caption);}}if(art==='introGuide')buildClearGuideBoard('messageClearGuideBoard');if(twoMoveLesson)buildTwoMoveLessonBoard('messageTwoMoveLessonBoard',twoMoveLesson);illustration.hidden=!art;lessonCopy.hidden=!twoMoveLesson;lessonRule.hidden=!twoMoveLesson;}
function renderMessageLesson(twoMoveLesson,illustration,lessonCopy,lessonRule){if(twoMoveLesson){renderTwoMoveLessonRule('messageTwoMoveLessonRule');renderTwoMoveLessonCopy('messageTwoMoveLessonCopy',twoMoveLesson);$('messageDialogText').after(illustration);illustration.before(lessonRule);illustration.after(lessonCopy);}else{lessonRule.replaceChildren();lessonCopy.replaceChildren();}}
function renderMessageQuiz(quiz){renderQuizInto({root:'messageQuiz',options:'messageQuizOptions',note:'messageQuizNote',title:'messageQuizTitle',question:'messageQuizQuestion'},quiz);}
function openMessageReview({resume=false,returnTarget=null}={}){messageDialogReturn=returnTarget;messageReviewEntries=buildMessageReviewEntries();if(resume){let lastKey='',lastClearKey='';try{lastKey=storage.get(MESSAGE_REVIEW_STORAGE_KEY)||'';lastClearKey=storage.get(MESSAGE_REVIEW_LAST_CLEAR_STORAGE_KEY)||'';}catch(_){}if(!lastClearKey&&isSatoriMastered()){const satoriEntry=messageReviewEntries.findIndex(entry=>entry.satori);if(satoriEntry>=0){messageReviewIndex=satoriEntry;const key=messageReviewEntryKey(messageReviewEntries[satoriEntry]);try{storage.set(MESSAGE_REVIEW_LAST_CLEAR_STORAGE_KEY,key);}catch(_){}}else messageReviewIndex=0;}else{const saved=messageReviewEntries.findIndex(entry=>messageReviewEntryKey(entry)===lastKey);messageReviewIndex=saved>=0?saved:0;}}else{const currentExtra=isMode('mastery'),currentIndex=isMode('mastery')?extraIndex:stageIndex;const exact=messageReviewEntries.findIndex(entry=>entry.extra===currentExtra&&entry.index===currentIndex);messageReviewIndex=exact>=0?exact:0;}renderMessageReview();$('messageDialog').hidden=false;$('closeMessages').focus();}
const MESSAGE_RENDERERS=Object.freeze({
  quiz:entry=>{configureMessageReviewHeader(entry);renderMessageQuiz(entry.quiz);},
  boardQuiz:entry=>{configureMessageReviewHeader(entry);renderBoardQuiz('messageBoardQuiz',clearContentAt(true,entry.index).boardQuiz);},
  text:entry=>{$('messageDialogText').hidden=false;configureMessageReviewHeader(entry);$('messageDialogTextBody').textContent=entry.text;}
});
function renderMessageReview(){const entry=messageReviewEntries[messageReviewIndex];if(!entry)return;const {art,twoMoveLesson}=prepareMessageReview(entry),view=messageReviewView(),{illustration,lessonCopy,lessonRule,roadmap,seal}=view;resetMessageReviewView(entry,view);if(isMilestoneMessage(entry)){const volume=milestoneVolume(entry),current=entry.master==='primary'?2:entry.master==='mastery'?6:Math.min(5,volume+2);if(entry.master!=='mastery')roadmap.innerHTML=masterRoadmapMarkup(current);milestoneRenderer(entry)(entry,view,volume);}else messageReviewRenderer(entry)(entry);renderMessageArtwork(art,twoMoveLesson,illustration,lessonCopy,lessonRule);renderMessageLesson(twoMoveLesson,illustration,lessonCopy,lessonRule);if(entry.master==='satoriIntro'||entry.master==='secondLapIntro'){seal.classList.remove('animate');void seal.offsetWidth;seal.classList.add('animate');}updateMessageReviewNavigation(entry);}
function renderPrimaryMilestone(entry,{seal,rankText,masterText,rules}){$('messageMasterSealLabel').textContent=masterPath().ranks[0];setSealColor(seal,0);configureMilestoneHeader(entry,tr('masterTitle'));rankText.hidden=false;rankText.textContent=rankEarnedText(masterPath().ranks[0]);masterText.hidden=false;masterText.textContent=tr('masterText');rules.hidden=false;rules.textContent=masterCommonRules();}
function renderMasteryMilestone(entry,{seal,rankText,masterText,boardNote}){$('messageMasterSealLabel').textContent=masterPath().ranks[3];setSealColor(seal,3);configureMilestoneHeader(entry,tr('masteryTitle'));rankText.hidden=false;rankText.textContent=rankEarnedText(masterPath().ranks[3]);masterText.hidden=false;masterText.textContent=tr('masteryText');boardNote.hidden=false;boardNote.textContent=tr('masteryBoardNote');}
function renderSatoriMilestone(entry,{seal,rankText,masterText}){$('messageMasterSealLabel').innerHTML=rankFrameSvg(tr('satoriRank'),false,5);setSealColor(seal,5);seal.classList.add('rank-frame-seal');configureMilestoneHeader(entry,tr('satoriTitle'));rankText.hidden=false;rankText.textContent=rankEarnedText(tr('satoriRank'));masterText.hidden=false;masterText.textContent=tr('satoriText');}
function renderAwakeningMilestone(entry,{seal,rankText,masterText,boardNote}){$('messageMasterSealLabel').innerHTML=rankFrameSvg(tr('awakenedRank'),false,6);setSealColor(seal,6);seal.classList.add('rank-frame-seal');configureMilestoneHeader(entry,tr('awakenedTitle'));rankText.hidden=false;rankText.textContent=rankEarnedText(tr('awakenedRank'));masterText.hidden=false;masterText.textContent=tr('satoriThanks');boardNote.hidden=false;boardNote.textContent=tr('threeDUnlockedText');}
function renderIntroMilestone(entry,{seal,masterText}){const data=INTRO_MILESTONE_COPY[entry.master];if(!data)return;seal.hidden=entry.master==='trainingWelcome';if(entry.master==='satoriIntro'){$('messageMasterSealLabel').innerHTML=satoriSealSvg();setSealColor(seal,5);}else if(entry.master==='secondLapIntro'){$('messageMasterSealLabel').textContent=secondLapMark();seal.classList.add('second-lap-mark');}configureMilestoneHeader(entry,tr(data[0]));masterText.hidden=false;masterText.textContent=tr(data[1]);}
function renderVolumeMilestone(entry,volume,{seal,rankText,masterText}){const nextRules=VOLUME_NEXT_RULES[currentLang]||[];const clearName=currentLang==='ja'?'名人への道・'+volumeLabel(volume)+'　'+masterSubtitle(volume):volumeLabel(volume)+'　'+masterSubtitle(volume);$('messageMasterSealLabel').textContent=rankForVolume(volume);setSealColor(seal,volume);configureMilestoneHeader(entry,tr('volumeClearTitle',{n:clearName}));rankText.hidden=false;rankText.textContent=rankEarnedText(rankForVolume(volume));masterText.hidden=false;masterText.textContent=nextRules[volume-1]||tr('volumeClearText');}
const MILESTONE_RENDERERS=Object.freeze({primary:(entry,view)=>renderPrimaryMilestone(entry,view),mastery:(entry,view)=>renderMasteryMilestone(entry,view),satori:(entry,view)=>renderSatoriMilestone(entry,view),awakening:(entry,view)=>renderAwakeningMilestone(entry,view),satoriIntro:(entry,view)=>renderIntroMilestone(entry,view),secondLapIntro:(entry,view)=>renderIntroMilestone(entry,view),trainingWelcome:(entry,view)=>renderIntroMilestone(entry,view),volume:(entry,view,volume)=>renderVolumeMilestone(entry,volume,view)});
// 公開native moduleの構文境界。
export {};
