import assert from 'node:assert/strict';
import { createDevelopmentRuntime } from '../src/main.mjs';
import { createPersistence } from '../src/state/persistence.mjs';
import { createBoardQuizCatalog } from '../src/data/board-quiz.mjs';
import { createMessageCatalog } from '../src/data/messages.mjs';
import { createSatoriCatalog } from '../src/data/satori.mjs';
import { createBoardCommands } from '../src/commands/board-commands.mjs';
import { createProgressionCommands } from '../src/commands/progression-commands.mjs';
import { createBoardView } from '../src/ui/board.mjs';
import { createMessagePresenter } from '../src/ui/messages.mjs';
import { createNavigationController } from '../src/ui/navigation.mjs';
import { createRenderCoordinator } from '../src/ui/render.mjs';
import { createEventBinder } from '../src/ui/events.mjs';
import { createSessionService } from '../src/runtime/session.mjs';
import { createUiLifecycle } from '../src/ui/lifecycle.mjs';
import { createUiStateView } from '../src/ui/state-view.mjs';
import { createSpeedUnlockService, DEFAULT_SPEED_UNLOCK_KEYS } from '../src/runtime/progression.mjs';
import { DEFAULT_SETTING_KEYS } from '../src/runtime/settings.mjs';

const runtime = createDevelopmentRuntime({ triangles: [{ cells: [0, 1, 2] }] });
assert.equal(runtime.board.stateCount, 2187);
assert.equal(typeof runtime.settings.initialize, 'function');
assert.equal(typeof runtime.audio.playTone, 'function');
assert.equal(typeof runtime.speedUnlocks.initialize, 'function');
assert.equal(DEFAULT_SETTING_KEYS.boardTheme, 'wake7-board-theme');
assert.equal(DEFAULT_SPEED_UNLOCK_KEYS.speedUnlocked, 'wake7-speed-unlocked');
const board = Uint8Array.from([0, 1, 2, 0, 1, 2, 1]);
assert.deepEqual(Array.from(runtime.board.decode(runtime.board.encode(board))), Array.from(board));
assert.deepEqual(Array.from(runtime.board.roll(runtime.board.roll(board, 0, 1), 0, -1)), Array.from(board));
assert.deepEqual(Array.from(runtime.board.swipe(runtime.board.swipe(board, 0, 1), 0, -1)), Array.from(board));
assert.deepEqual(Array.from(runtime.board.click(runtime.board.click(board, 0, 1), 0, -1)), Array.from(board));
assert.equal(runtime.progression.indexFor({ mode: 'mastery', masteryIndex: 4 }), 4);
assert.equal(runtime.progression.uiPolicy({ mode: 'tutorial' }).assisted, true);
let notified = false;
const unsubscribe = runtime.store.subscribe(() => { notified = true; });
runtime.store.update({ navigation: { mode: 'tutorial', lap: 1 } });
runtime.store.updateSection('settings', { language: 'ja' });
assert.equal(runtime.store.state.settings.language, 'ja');
unsubscribe();
assert.equal(notified, true);
const memory = new Map();
const storage = { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, value) };
const persistence = createPersistence({ storage, create: value => value });
assert.equal(persistence.write({ version: 1, ok: true }), true);
assert.deepEqual(persistence.read(), { version: 1, ok: true });
const messages = createMessageCatalog({ welcome: { dialog: 'trainingWelcome' }, lesson: { tip: { ja: 'ok' } } });
assert.equal(messages.has('welcome'), true);
assert.equal(messages.descriptor('welcome').timing, 'afterClear');
const satori = createSatoriCatalog([{ state: 4, par: 2 }, { state: 7, par: 3 }]);
assert.deepEqual(satori.byDepth(2), [{ state: 4, par: 2 }]);
const quiz = createBoardQuizCatalog({ ja: { title: '盤面クイズ' } });
assert.equal(quiz.forLanguage('en').title, '盤面クイズ');
const runtimeData = createDevelopmentRuntime({ data: { clearContent: { x: { tip: { ja: 'x' } } }, satoriStages: [{ state: 0, par: 1 }], boardQuizCopy: { ja: { title: 'q' } } } }).data;
assert.equal(runtimeData.messages.has('x'), true);
assert.equal(runtimeData.satori.length, 1);
assert.equal(runtimeData.boardQuiz.forLanguage('ja').title, 'q');
let boardState = Uint8Array.from([0, 0, 0]);
const boardCommands = createBoardCommands({
  getBoard: () => boardState,
  applyMove: (current, triangleIndex, direction) => ({ board: Uint8Array.from(current, value => value + direction), triangleIndex }),
  setBoard: next => { boardState = next; }
});
assert.equal(boardCommands.apply(0, 1).triangleIndex, 0);
assert.deepEqual(Array.from(boardState), [1, 1, 1]);
let progressionCalls = 0;
const progressionCommands = createProgressionCommands({ startSpeedRun: () => { progressionCalls++; return { ok: true }; } });
assert.deepEqual(progressionCommands.startSpeedRun(), { ok: true });
assert.equal(progressionCalls, 1);
assert.equal(createBoardView({}).build(), false);
assert.equal(createMessagePresenter({}).show('missing'), null);
const navigation = createNavigationController({ store: runtime.store, normalize: runtime.progression.normalizeNavigation });
assert.equal(navigation.setMode('tutorial', { tutorialStep: 2 }).ok, true);
assert.equal(runtime.store.state.navigation.mode, 'tutorial');
assert.equal(runtime.commands.progression.navigate({ mode: 'stage', stageIndex: 3 }).ok, true);
assert.equal(runtime.store.state.navigation.stageIndex, 3);
for (const stageIndex of [0, 1, 2, 3]) {
  const result = runtime.commands.progression.navigate({ mode: 'stage', stageIndex });
  assert.equal(result.ok, true);
  assert.equal(runtime.store.state.navigation.stageIndex, stageIndex);
}
assert.equal(runtime.commands.progression.navigate({ mode: 'speed', stageIndex: 0 }).ok, true);
assert.equal(runtime.store.state.navigation.mode, 'speed');
assert.equal(runtime.commands.progression.navigate({ mode: 'stage', stageIndex: 0 }).ok, true);
let renderCount = 0;
const renderer = createRenderCoordinator({ store: runtime.store, renderers: { navigation: () => { renderCount++; } } });
assert.equal(renderer.render().ok, true);
const disconnect = renderer.connect();
runtime.store.updateSection('navigation', { stageIndex: 4 });
disconnect();
assert.equal(renderCount, 2);
const eventTarget = { added: [], addEventListener(type, listener, options) { this.added.push({ type, listener, options }); }, removeEventListener(type, listener) { this.added = this.added.filter(item => item.type !== type || item.listener !== listener); } };
const events = createEventBinder({ target: eventTarget, handlers: { change: () => {} } });
assert.equal(events.bindAll(), 1);
assert.equal(events.size, 1);
assert.equal(events.unbindAll(), 1);
assert.equal(events.size, 0);
let savedSession = null;
const session = createSessionService({ persistence: { read: () => savedSession, write: value => { savedSession = value; return true; } }, normalize: value => ({ ...value, normalized: true }) });
assert.equal(session.save({ mode: 'stage' }), true);
assert.deepEqual(session.current, { mode: 'stage', normalized: true });
assert.deepEqual(session.load(), { mode: 'stage', normalized: true });
assert.equal(session.clear(), true);
assert.equal(session.current, null);
assert.equal(typeof runtime.session.load, 'function');
let starts = 0; let stops = 0; let bound = 0; let unbound = 0; let disconnected = 0;
const lifecycle = createUiLifecycle({ events: { bindAll: () => { bound++; }, unbindAll: () => { unbound++; } }, renderer: { connect: () => () => { disconnected++; } }, onStart: () => { starts++; }, onStop: () => { stops++; } });
assert.equal(lifecycle.start(), true);
assert.equal(lifecycle.start(), false);
assert.equal(lifecycle.active, true);
assert.equal(lifecycle.stop(), true);
assert.equal(lifecycle.stop(), false);
assert.deepEqual({ starts, stops, bound, unbound, disconnected }, { starts: 1, stops: 1, bound: 1, unbound: 1, disconnected: 1 });
const stateView = createUiStateView({ store: runtime.store, select: state => ({ mode: state.navigation.mode, index: state.navigation.stageIndex }) });
assert.deepEqual(stateView.snapshot(), { mode: 'stage', index: 4 });
let viewMode = '';
const stopView = createUiStateView({ store: runtime.store, select: state => state.navigation.mode, onChange: value => { viewMode = value; } }).subscribe();
runtime.commands.progression.navigate({ mode: 'mastery', masteryIndex: 2 });
stopView();
assert.equal(viewMode, 'mastery');
console.log('Validated development ES module entry point.');
