import assert from 'node:assert/strict';
import { createDevelopmentRuntime } from '../src/main.mjs';
import { createPersistence } from '../src/state/persistence.mjs';
import { createBoardQuizCatalog } from '../src/data/board-quiz.mjs';
import { createMessageCatalog } from '../src/data/messages.mjs';
import { createSatoriCatalog } from '../src/data/satori.mjs';

const runtime = createDevelopmentRuntime({ triangles: [{ cells: [0, 1, 2] }] });
assert.equal(runtime.board.stateCount, 2187);
const board = Uint8Array.from([0, 1, 2, 0, 1, 2, 1]);
assert.deepEqual(Array.from(runtime.board.decode(runtime.board.encode(board))), Array.from(board));
assert.deepEqual(Array.from(runtime.board.roll(runtime.board.roll(board, 0, 1), 0, -1)), Array.from(board));
assert.deepEqual(Array.from(runtime.board.swipe(runtime.board.swipe(board, 0, 1), 0, -1)), Array.from(board));
assert.deepEqual(Array.from(runtime.board.click(runtime.board.click(board, 0, 1), 0, -1)), Array.from(board));
assert.equal(runtime.progression.indexFor({ mode: 'mastery', masteryIndex: 4 }), 4);
assert.equal(runtime.progression.uiPolicy({ mode: 'tutorial' }).assisted, true);
let notified = false;
const unsubscribe = runtime.store.subscribe(() => { notified = true; });
runtime.store.update({ navigation: { mode: 'tutorial', lap: 1 } });
runtime.store.updateSection('settings', { language: 'ja' });
assert.equal(runtime.store.state.settings.language, 'ja');
unsubscribe();
assert.equal(notified, true);
const memory = new Map();
const storage = { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, value) };
const persistence = createPersistence({ storage, create: value => value });
assert.equal(persistence.write({ version: 1, ok: true }), true);
assert.deepEqual(persistence.read(), { version: 1, ok: true });
const messages = createMessageCatalog({ welcome: { dialog: 'trainingWelcome' }, lesson: { tip: { ja: 'ok' } } });
assert.equal(messages.has('welcome'), true);
assert.equal(messages.descriptor('welcome').timing, 'afterClear');
const satori = createSatoriCatalog([{ state: 4, par: 2 }, { state: 7, par: 3 }]);
assert.deepEqual(satori.byDepth(2), [{ state: 4, par: 2 }]);
const quiz = createBoardQuizCatalog({ ja: { title: '盤面クイズ' } });
assert.equal(quiz.forLanguage('en').title, '盤面クイズ');
const runtimeData = createDevelopmentRuntime({ data: { clearContent: { x: { tip: { ja: 'x' } } }, satoriStages: [{ state: 0, par: 1 }], boardQuizCopy: { ja: { title: 'q' } } } }).data;
assert.equal(runtimeData.messages.has('x'), true);
assert.equal(runtimeData.satori.length, 1);
assert.equal(runtimeData.boardQuiz.forLanguage('ja').title, 'q');
console.log('Validated development ES module entry point.');
